//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterIdentityProviderMapper) DeepCopyInto(out *ImporterIdentityProviderMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterIdentityProviderMapper.
func (in *ImporterIdentityProviderMapper) DeepCopy() *ImporterIdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(ImporterIdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImporterIdentityProviderMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterIdentityProviderMapperList) DeepCopyInto(out *ImporterIdentityProviderMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImporterIdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterIdentityProviderMapperList.
func (in *ImporterIdentityProviderMapperList) DeepCopy() *ImporterIdentityProviderMapperList {
	if in == nil {
		return nil
	}
	out := new(ImporterIdentityProviderMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImporterIdentityProviderMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterIdentityProviderMapperObservation) DeepCopyInto(out *ImporterIdentityProviderMapperObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterIdentityProviderMapperObservation.
func (in *ImporterIdentityProviderMapperObservation) DeepCopy() *ImporterIdentityProviderMapperObservation {
	if in == nil {
		return nil
	}
	out := new(ImporterIdentityProviderMapperObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterIdentityProviderMapperParameters) DeepCopyInto(out *ImporterIdentityProviderMapperParameters) {
	*out = *in
	if in.AttributeFriendlyName != nil {
		in, out := &in.AttributeFriendlyName, &out.AttributeFriendlyName
		*out = new(string)
		**out = **in
	}
	if in.AttributeName != nil {
		in, out := &in.AttributeName, &out.AttributeName
		*out = new(string)
		**out = **in
	}
	if in.ClaimName != nil {
		in, out := &in.ClaimName, &out.ClaimName
		*out = new(string)
		**out = **in
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IdentityProviderAlias != nil {
		in, out := &in.IdentityProviderAlias, &out.IdentityProviderAlias
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.UserAttribute != nil {
		in, out := &in.UserAttribute, &out.UserAttribute
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterIdentityProviderMapperParameters.
func (in *ImporterIdentityProviderMapperParameters) DeepCopy() *ImporterIdentityProviderMapperParameters {
	if in == nil {
		return nil
	}
	out := new(ImporterIdentityProviderMapperParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterIdentityProviderMapperSpec) DeepCopyInto(out *ImporterIdentityProviderMapperSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterIdentityProviderMapperSpec.
func (in *ImporterIdentityProviderMapperSpec) DeepCopy() *ImporterIdentityProviderMapperSpec {
	if in == nil {
		return nil
	}
	out := new(ImporterIdentityProviderMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterIdentityProviderMapperStatus) DeepCopyInto(out *ImporterIdentityProviderMapperStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterIdentityProviderMapperStatus.
func (in *ImporterIdentityProviderMapperStatus) DeepCopy() *ImporterIdentityProviderMapperStatus {
	if in == nil {
		return nil
	}
	out := new(ImporterIdentityProviderMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToRoleIdentityProviderMapper) DeepCopyInto(out *ToRoleIdentityProviderMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToRoleIdentityProviderMapper.
func (in *ToRoleIdentityProviderMapper) DeepCopy() *ToRoleIdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(ToRoleIdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToRoleIdentityProviderMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToRoleIdentityProviderMapperList) DeepCopyInto(out *ToRoleIdentityProviderMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToRoleIdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToRoleIdentityProviderMapperList.
func (in *ToRoleIdentityProviderMapperList) DeepCopy() *ToRoleIdentityProviderMapperList {
	if in == nil {
		return nil
	}
	out := new(ToRoleIdentityProviderMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToRoleIdentityProviderMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToRoleIdentityProviderMapperObservation) DeepCopyInto(out *ToRoleIdentityProviderMapperObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToRoleIdentityProviderMapperObservation.
func (in *ToRoleIdentityProviderMapperObservation) DeepCopy() *ToRoleIdentityProviderMapperObservation {
	if in == nil {
		return nil
	}
	out := new(ToRoleIdentityProviderMapperObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToRoleIdentityProviderMapperParameters) DeepCopyInto(out *ToRoleIdentityProviderMapperParameters) {
	*out = *in
	if in.AttributeFriendlyName != nil {
		in, out := &in.AttributeFriendlyName, &out.AttributeFriendlyName
		*out = new(string)
		**out = **in
	}
	if in.AttributeName != nil {
		in, out := &in.AttributeName, &out.AttributeName
		*out = new(string)
		**out = **in
	}
	if in.AttributeValue != nil {
		in, out := &in.AttributeValue, &out.AttributeValue
		*out = new(string)
		**out = **in
	}
	if in.ClaimName != nil {
		in, out := &in.ClaimName, &out.ClaimName
		*out = new(string)
		**out = **in
	}
	if in.ClaimValue != nil {
		in, out := &in.ClaimValue, &out.ClaimValue
		*out = new(string)
		**out = **in
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IdentityProviderAlias != nil {
		in, out := &in.IdentityProviderAlias, &out.IdentityProviderAlias
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToRoleIdentityProviderMapperParameters.
func (in *ToRoleIdentityProviderMapperParameters) DeepCopy() *ToRoleIdentityProviderMapperParameters {
	if in == nil {
		return nil
	}
	out := new(ToRoleIdentityProviderMapperParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToRoleIdentityProviderMapperSpec) DeepCopyInto(out *ToRoleIdentityProviderMapperSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToRoleIdentityProviderMapperSpec.
func (in *ToRoleIdentityProviderMapperSpec) DeepCopy() *ToRoleIdentityProviderMapperSpec {
	if in == nil {
		return nil
	}
	out := new(ToRoleIdentityProviderMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToRoleIdentityProviderMapperStatus) DeepCopyInto(out *ToRoleIdentityProviderMapperStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToRoleIdentityProviderMapperStatus.
func (in *ToRoleIdentityProviderMapperStatus) DeepCopy() *ToRoleIdentityProviderMapperStatus {
	if in == nil {
		return nil
	}
	out := new(ToRoleIdentityProviderMapperStatus)
	in.DeepCopyInto(out)
	return out
}
