//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeIdentityProviderMapper) DeepCopyInto(out *AttributeIdentityProviderMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeIdentityProviderMapper.
func (in *AttributeIdentityProviderMapper) DeepCopy() *AttributeIdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(AttributeIdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttributeIdentityProviderMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeIdentityProviderMapperList) DeepCopyInto(out *AttributeIdentityProviderMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AttributeIdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeIdentityProviderMapperList.
func (in *AttributeIdentityProviderMapperList) DeepCopy() *AttributeIdentityProviderMapperList {
	if in == nil {
		return nil
	}
	out := new(AttributeIdentityProviderMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttributeIdentityProviderMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeIdentityProviderMapperObservation) DeepCopyInto(out *AttributeIdentityProviderMapperObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeIdentityProviderMapperObservation.
func (in *AttributeIdentityProviderMapperObservation) DeepCopy() *AttributeIdentityProviderMapperObservation {
	if in == nil {
		return nil
	}
	out := new(AttributeIdentityProviderMapperObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeIdentityProviderMapperParameters) DeepCopyInto(out *AttributeIdentityProviderMapperParameters) {
	*out = *in
	if in.AttributeName != nil {
		in, out := &in.AttributeName, &out.AttributeName
		*out = new(string)
		**out = **in
	}
	if in.AttributeValue != nil {
		in, out := &in.AttributeValue, &out.AttributeValue
		*out = new(string)
		**out = **in
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IdentityProviderAlias != nil {
		in, out := &in.IdentityProviderAlias, &out.IdentityProviderAlias
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.UserSession != nil {
		in, out := &in.UserSession, &out.UserSession
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeIdentityProviderMapperParameters.
func (in *AttributeIdentityProviderMapperParameters) DeepCopy() *AttributeIdentityProviderMapperParameters {
	if in == nil {
		return nil
	}
	out := new(AttributeIdentityProviderMapperParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeIdentityProviderMapperSpec) DeepCopyInto(out *AttributeIdentityProviderMapperSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeIdentityProviderMapperSpec.
func (in *AttributeIdentityProviderMapperSpec) DeepCopy() *AttributeIdentityProviderMapperSpec {
	if in == nil {
		return nil
	}
	out := new(AttributeIdentityProviderMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeIdentityProviderMapperStatus) DeepCopyInto(out *AttributeIdentityProviderMapperStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeIdentityProviderMapperStatus.
func (in *AttributeIdentityProviderMapperStatus) DeepCopy() *AttributeIdentityProviderMapperStatus {
	if in == nil {
		return nil
	}
	out := new(AttributeIdentityProviderMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleIdentityProviderMapper) DeepCopyInto(out *RoleIdentityProviderMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleIdentityProviderMapper.
func (in *RoleIdentityProviderMapper) DeepCopy() *RoleIdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(RoleIdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleIdentityProviderMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleIdentityProviderMapperList) DeepCopyInto(out *RoleIdentityProviderMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoleIdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleIdentityProviderMapperList.
func (in *RoleIdentityProviderMapperList) DeepCopy() *RoleIdentityProviderMapperList {
	if in == nil {
		return nil
	}
	out := new(RoleIdentityProviderMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleIdentityProviderMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleIdentityProviderMapperObservation) DeepCopyInto(out *RoleIdentityProviderMapperObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleIdentityProviderMapperObservation.
func (in *RoleIdentityProviderMapperObservation) DeepCopy() *RoleIdentityProviderMapperObservation {
	if in == nil {
		return nil
	}
	out := new(RoleIdentityProviderMapperObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleIdentityProviderMapperParameters) DeepCopyInto(out *RoleIdentityProviderMapperParameters) {
	*out = *in
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IdentityProviderAlias != nil {
		in, out := &in.IdentityProviderAlias, &out.IdentityProviderAlias
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleIdentityProviderMapperParameters.
func (in *RoleIdentityProviderMapperParameters) DeepCopy() *RoleIdentityProviderMapperParameters {
	if in == nil {
		return nil
	}
	out := new(RoleIdentityProviderMapperParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleIdentityProviderMapperSpec) DeepCopyInto(out *RoleIdentityProviderMapperSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleIdentityProviderMapperSpec.
func (in *RoleIdentityProviderMapperSpec) DeepCopy() *RoleIdentityProviderMapperSpec {
	if in == nil {
		return nil
	}
	out := new(RoleIdentityProviderMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleIdentityProviderMapperStatus) DeepCopyInto(out *RoleIdentityProviderMapperStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleIdentityProviderMapperStatus.
func (in *RoleIdentityProviderMapperStatus) DeepCopy() *RoleIdentityProviderMapperStatus {
	if in == nil {
		return nil
	}
	out := new(RoleIdentityProviderMapperStatus)
	in.DeepCopyInto(out)
	return out
}
